name: 'echo randomNum by lNEWBEEl'
description: 'This Action will output a random number'
author: 'MingXi Feng'
branding:
  icon: 'clock'
  color: 'gray-dark'

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - name: 'Checkout Repository'
      uses: 'actions/checkout@v2'
      with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        repository: 'lNEWBEEl/echorandomnum'
      
    - name: 'random-number-generator'
      run: echo "random-id=$(echo $RANDOM)"
      shell: bash
      
    - name: 'random-js'
      run: |
        node ./randomnum.js
      shell: bash
      
    - name: 'curl-page'
      run: |
        curl https://www.baidu.com
      shell: bash
