name: 'echo randomNum by lNEWBEEl'
description: 'This Action will output a random number'
author: 'MingXi Feng'
branding:
  icon: 'clock'
  color: 'gray-dark'

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - id: random-number-generator
      run: echo "random-id=$(echo $RANDOM)"
      shell: bash
      
    - id: random-js
      run: |
        node randomnum.js
      shell: bash
      
    - id: curl-page
      run: |
        curl https://www.baidu.com
      shell: bash
